# This is a basic workflow to help you get started with Actions

name: CI CD

on:
  push:
    branches: [ release ]

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and build
        run: |
          npm install
          npm run build
          
      - name: Release
        run: |

